### ISSUE TITLE
Cannot import cachedproperty from descriptors

### ISSUE THREAD

**Issue by alexhendrik** [workforce-data-initiative/skills-ml#267]
Sorry if it's a bad question, but I've been stuck on this for over a week and see no other way out.  I've been trying to run the example skill evaluation loop to see how it works and later implement it in my own work.  

However, I cannot get past the fuzzy skill matching due to there not existing a 'descriptors' package and thus it cant import cached property.  I have tried substituting this with the cached-property package from PyPi but that did not work.  I would greatly appreciate some help!

**Comment by thcrock** [comment]
The library name should be 'dickens'. Our apologies if it's not in the requirements.txt and we'll fix that

**Comment by alexhendrik** [comment]
I did have it installed and reinstall did not help.  However, what did fix the issue I was having was placing the descriptors.py file into the virtual environment instead of in the global python packages.  I guess PyCharm was not particularly happy about my global installation and after reinstalling it within the IDE as well, the error went away.

Thank you so much! I will be closing the issue now.
