### ISSUE TITLE
Integrate tox, travis, codecov, readthedocs

### ISSUE THREAD

**Issue by thcrock** [workforce-data-initiative/skills-ml#5]
We have the checklist of public repository TODOs that we should implement:

Tox to automate testing (we may only care about python3 here)
Travis to run the tests when we push to master
Codecov
Readthedocs? (unsure, we should figure out if we just want to centralize documentation like this in our wikis)
I might be missing something else here, but 'cookiecutter' is used elsewhere in DSaPP to take care of this stuff

**Comment by robinsonkwame** [comment]
Strong recommend to only care about python3 for how it handles unicode alone, since we're working with large collections of unicode, non unicode semi strcutured text.

**Comment by thcrock** [comment]
DOne in https://github.com/workforce-data-initiative/skills-ml/pull/12
